version: "3.4"

services:
  api:
    image: ${DOCKER_USER}/api:latest
    container_name: api
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - mongodb
    volumes:
      - ./config/:/root/config/
      - ./template/:/root/template/
      - ./:/github.com/${DOCKER_USER}/timeline-server/

  mongodb:
    image: mongo:6.0.4-jammy
    container_name: mongodb
    environment:
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - .data:/data/db
    ports:
      - 27017:27017
