// Code generated by MockGen. DO NOT EDIT.
// Source: competition.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	context "context"
	reflect "reflect"
	domain "timeline/internal/domain"

	gin "github.com/gin-gonic/gin"
	gomock "github.com/golang/mock/gomock"
)

// MockCompetitionInterface is a mock of CompetitionInterface interface.
type MockCompetitionInterface struct {
	ctrl     *gomock.Controller
	recorder *MockCompetitionInterfaceMockRecorder
}

// MockCompetitionInterfaceMockRecorder is the mock recorder for MockCompetitionInterface.
type MockCompetitionInterfaceMockRecorder struct {
	mock *MockCompetitionInterface
}

// NewMockCompetitionInterface creates a new mock instance.
func NewMockCompetitionInterface(ctrl *gomock.Controller) *MockCompetitionInterface {
	mock := &MockCompetitionInterface{ctrl: ctrl}
	mock.recorder = &MockCompetitionInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCompetitionInterface) EXPECT() *MockCompetitionInterfaceMockRecorder {
	return m.recorder
}

// GetCompetitionById mocks base method.
func (m *MockCompetitionInterface) GetCompetitionById(ctx context.Context, id int) (domain.Competition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCompetitionById", ctx, id)
	ret0, _ := ret[0].(domain.Competition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCompetitionById indicates an expected call of GetCompetitionById.
func (mr *MockCompetitionInterfaceMockRecorder) GetCompetitionById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCompetitionById", reflect.TypeOf((*MockCompetitionInterface)(nil).GetCompetitionById), ctx, id)
}

// GetCompetitions mocks base method.
func (m *MockCompetitionInterface) GetCompetitions(ctx *gin.Context) ([]domain.Competition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCompetitions", ctx)
	ret0, _ := ret[0].([]domain.Competition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCompetitions indicates an expected call of GetCompetitions.
func (mr *MockCompetitionInterfaceMockRecorder) GetCompetitions(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCompetitions", reflect.TypeOf((*MockCompetitionInterface)(nil).GetCompetitions), ctx)
}
